import type { NextPage } from "next";
import Head from "next/head";
import { useDispatch } from "react-redux";
import { animated, useTransition, config } from "react-spring";
import styled from "styled-components";
import dynamic from "next/dynamic";

import { ship, review, pay } from "@/store/stepperSlicer";
import { useTypedSelector } from "@/store/index";
import { selectStep } from "@/store/stepperSlicer";
import usePrevious from "@/components/Hooks/usePrevious";

// import Shipping from "./shipping/index";
// import Order from "./review";
// import Stripe from "./stripewrap";

const Order = dynamic(() => import("./review"), {
  suspense: true,
});
const Shipping = dynamic(() => import("./shipping/index"), {
  suspense: true,
});
const Stripe = dynamic(() => import("./stripewrap"), {
  suspense: true,
});

const Checkout: NextPage = () => {
  const dispatch = useDispatch();
  const { step } = useTypedSelector(selectStep);

  const stepComponent = [
    <Shipping key="1" />,
    <Order key="2" />,
    <Stripe key="3" />,
  ];

  const VW = window.innerWidth;
  const prevstep = usePrevious(step);
  const reverse = prevstep! > step;

  const stepTransition = useTransition(step, {
    from: { opacity: 1, x: reverse ? -VW : VW },
    enter: { opacity: 1, x: 0 },
    leave: { opacity: 1, x: reverse ? VW : -VW },
    config: config.slow,
  });

  return (
    <div>
      <Head>
        <title>Checkout Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Steps>
          <div
            className={`${step >= 0 ? "past" : ""}`}
            onClick={() => dispatch(ship())}
          >
            1 SHIP
          </div>
          <div
            className={`${step > 0 ? "past" : ""}`}
            onClick={() => dispatch(review())}
          >
            2 REVIEW
          </div>
          <div
            className={`${step > 1 ? "past" : ""}`}
            onClick={() => dispatch(pay())}
          >
            3 PAYMENT
          </div>
        </Steps>

        <StepCanva>
          {stepTransition((styles, activeStep) => (
            <animated.div style={styles}>
              {stepComponent[activeStep]}
            </animated.div>
          ))}
        </StepCanva>
      </Main>
    </div>
  );
};

export default Checkout;

const Main = styled.main`
  min-height: 100vh;
`;

const Steps = styled(animated.div)`
  z-index: 3;
  // height: 50px;
  width: 100vw;
  margin: 0px auto;
  padding-top: 100px;

  box-shadow: 2px 2px 20px hsla(0, 0%, 0%, 0.5);

  display: flex;
  justify-content: center;

  div {
    max-width: 200px;
    width: 100%;
    height: 30px;
    margin: 10px;

    transition: 1s;
    box-shadow: 2px 2px 12px hsla(0, 0%, 0%, 0.3);
    color: hsla(260, 100%, 50%, 0.1);
    border-radius: 5px;
    border: 2px solid hsla(260, 100%, 50%, 0);
    text-transform: uppercase;
    font-size: 12px;

    display: grid;
    place-items: center;
  }
  .past {
    transition: 0.3s;
    border: 2px solid hsla(260, 100%, 50%, 1);
    color: hsla(260, 100%, 50%, 1);
  }
`;

const StepCanva = styled.div`
  overflow: hidden;
  margin: 10px;

  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;

  div {
    grid-column: 1;
    grid-row: 1;
  }
`;
