import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { fetchProducts } from "../store/productsSlicer";
import Hero from "../components/Home/Hero";
import ProductCards from "../components/Home/ProductCards";
import axios from "axios";
import { AppDispatch } from "@/store";
import Footer from "@/components/General/Footer";

const Home: NextPage = () => {
  const dispatch: AppDispatch = useDispatch();
  useEffect(() => {
    dispatch(fetchProducts());
  }, [dispatch]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <ProductCards />
      </main>

      <Footer />
    </div>
  );
};

{
  /* export async function getServerSideProps() {
    const url =
        process.env["NODE_ENV"] === "development"
            ? "http://localhost:3000"
            : "";
    const productsUrl = () => `${url}/api/products`;
    const { data: productsList } = await axios.get(productsUrl());

    return {
        props: { productsList },
    };
} */
}

export default Home;
