import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useDispatch } from "react-redux";
import { fetchProducts } from "../store/productsSlicer";

import ProductCards from "../components/Home/ProductCards";

import Footer from "@/components/General/Footer";
import Hero from "@/components/Home/Hero";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <ProductCards />
      </main>

      <Footer />
    </div>
  );
};

{
  /* export async function getServerSideProps() {
    const url =
        process.env["NODE_ENV"] === "development"
            ? "http://localhost:3000"
            : "";
    const productsUrl = () => `${url}/api/products`;
    const { data: productsList } = await axios.get(productsUrl());

    return {
        props: { productsList },
    };
} */
}

export default Home;
